#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
    /config/{logs,crontabs}

if [ ! -f "/config/rsync.sh" ]; then
    echo "copying default rsync script"
    cp /defaults/rsync.sh /config/
else
    echo "using existing rsync script"
fi

# permissions
chown -R abc:abc \
    /config
