name: Build Image

on: [push, pull_request, workflow_dispatch]

env:
  ENDPOINT: "aptalca/rsync"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Build image
        run: |
          docker build --no-cache -t ${{ github.sha }} .
      - name: Tag image
        if: ${{ github.ref == format('refs/heads/master') }}
        run: |
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:latest
#      - name: Login to GitHub Container Registry
#        if: ${{ github.ref == format('refs/heads/master') }}
#        run: |
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u aptalca --password-stdin
      - name: Push tags to GitHub Container Registry
        if: ${{ github.ref == format('refs/heads/master') }}
        run: |
          docker push ghcr.io/${ENDPOINT}:${{ github.sha }}
          docker push ghcr.io/${ENDPOINT}:latest