#!/usr/bin/with-contenv bash

if [ ! -f "/config/rsync.sh" ]; then
  echo "copying default rsync script"
  cp /app/script/rsync.sh /config/
else
  echo "using existing rsync script"
fi

# permissions
chown -R abc:abc \
	/config
